services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5041:5041"
    environment:
      - ASPNETCORE_URLS=http://+:5041
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: localbookstore
      MYSQL_USER: bookstoredbadmin
      MYSQL_PASSWORD: test@123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
